# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "Home Base" do
source 'https://github.com/CocoaPods/Specs.git'
pod 'AFNetworking', '~> 2.0'
pod 'libsodium-ios', '~> 0.4.5'
pod 'SlabClient', :path => '../../ios-lib/SlabClient'
pod 'SSKeychain'
end

target "Home BaseTests" do

end

