# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "SlabClient" do
source 'https://github.com/CocoaPods/Specs.git'
pod 'AFNetworking', '~> 2.0'
pod 'libsodium-ios', '~> 0.4.5'
end

#target "SlabClientTests" do

#end

