# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "ToDoList" do
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.0'
pod 'SlabClient', :path => '../../ios-lib/SlabClient'
pod 'SBJson', '~> 4.0.0'

end

target "ToDoListTests" do

end

