# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "ToDoList" do
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
pod 'SlabClient', :path => '../../ios-lib/SlabClient'
pod 'SBJson', '~> 4.0.0'
pod 'APAddressBook', '~> 0.1.4'
pod 'Lockbox', '~> 2.0.0'
pod 'NWPusher', '~> 0.6.0'

end

target "ToDoListTests" do

end

